### ISSUE TITLE
'download' lxc template only available in trusty

### ISSUE THREAD

**Issue by oker1** [fgrehm/vagrant-lxc-base-boxes#1]
If replacing it is not possible this limitation should be noted in the readme.

**Comment by fgrehm** [comment]
[I've stepped down as a maintainer of the plugin](https://github.com/fgrehm/vagrant-lxc/issues/375) and I'm no longer maintaining this repo. Feel free to use it as a starting point for your own boxes and if you need any help with that just LMK! :beers:
