### ISSUE TITLE
failed to update jessie box

### ISSUE THREAD

**Issue by erickeller** [fgrehm/vagrant-lxc-base-boxes#10]
Hi, I was trying out your script and the following error occured:

make jessie                                                                                            [master] 
==> [jessie] Building box to 'output/2014-05-16/vagrant-lxc-jessie-amd64.box'...
==> [jessie] The 'vagrant-base-jessie-amd64' container already exists, do you want to continue building the box? [Y/n] Y
==> [jessie] Do you want to rebuild the 'vagrant-base-jessie-amd64' container? [y/N] 
    [jessie] Reusing existing container...
    [jessie] Running [/usr/sbin/update-rc.d -f checkroot-bootclean.sh remove] inside 'vagrant-base-jessie-amd64' container...
    [jessie] Running [/usr/sbin/update-rc.d -f mountall-bootclean.sh remove] inside 'vagrant-base-jessie-amd64' container...
    [jessie] Running [/usr/sbin/update-rc.d -f mountnfs-bootclean.sh remove] inside 'vagrant-base-jessie-amd64' container...
    [jessie] Running [/usr/sbin/locale-gen en_US.UTF-8] inside 'vagrant-base-jessie-amd64' container...
    [jessie] Running [update-locale LANG=en_US.UTF-8] inside 'vagrant-base-jessie-amd64' container...
==> [jessie] Installing extra packages and upgrading
    [jessie] Sleeping for 5 seconds...
    [jessie] Running [apt-get update] inside 'vagrant-base-jessie-amd64' container...
    [jessie] Running [apt-get install vim nfs-common curl wget man-db bash-completion python-software-properties ca-certificates sudo -y --force-yes] inside 'vagrant-base-jessie-amd64' container...
make: *** [jessie] Error 100

Cheers

**Comment by fgrehm** [comment]
[I've stepped down as a maintainer of the plugin](https://github.com/fgrehm/vagrant-lxc/issues/375) and I'm no longer maintaining this repo. Feel free to use it as a starting point for your own boxes and if you need any help with that just LMK! :beers:
