### ISSUE TITLE
Remove generated dhcp leases from base boxes

### ISSUE THREAD

**Issue by fgrehm** [fgrehm/vagrant-lxc-base-boxes#12]
As in https://github.com/jedi4ever/veewee/blob/master/templates/ubuntu-14.04-server-amd64/cleanup.sh#L6-L7

**Comment by enricostano** [comment]
Any news about this? I'm having an hard time trying to set static IP address on `fgrehm/trusty64-lxc` box.

**Comment by fgrehm** [comment]
[I've stepped down as a maintainer of the plugin](https://github.com/fgrehm/vagrant-lxc/issues/375) and I'm no longer maintaining this repo. Feel free to use it as a starting point for your own boxes and if you need any help with that just LMK! :beers:

**Comment by enricostano** [comment]
Thanks! Just don't using vagrant anymore. Bye!
