### ISSUE TITLE
Can we build i386 images too? 

### ISSUE THREAD

**Issue by yukron** [fgrehm/vagrant-lxc-base-boxes#17]
I would like to build i386 boxes, what should be done to achieve this?

**Comment by fgrehm** [comment]
[I've stepped down as a maintainer of the plugin](https://github.com/fgrehm/vagrant-lxc/issues/375) and I'm no longer maintaining this repo. Feel free to use it as a starting point for your own boxes and if you need any help with that just LMK! :beers:
