### ISSUE TITLE
Improve initial network settings to allow static IPs

### ISSUE THREAD

**Issue by micw** [fgrehm/vagrant-lxc-base-boxes#18]
To allow static IPs in the machines, please add the following:

- default dns should point to something like 8.8.8.8 so that name resolution works if there's no dhcp
- add a script to the image that replaces /etc/network/interfaces with a version without eth0 settings. This script can simply be run with lxc.hook.start to switch dhcp off.

**Comment by fgrehm** [comment]
[I've stepped down as a maintainer of the plugin](https://github.com/fgrehm/vagrant-lxc/issues/375) and I'm no longer maintaining this repo. Feel free to use it as a starting point for your own boxes and if you need any help with that just LMK! :beers:
