### ISSUE TITLE
Can't build basebox on debian wheezy

### ISSUE THREAD

**Issue by oker1** [fgrehm/vagrant-lxc-base-boxes#2]
I've downloaded the lxc-download template, but it's not working on debian wheezy. I'll debug this, I think its related to the different lxc versions, debian has 0.8.0. At this point it should be noted that only Ubuntu is tested :)

**Comment by fgrehm** [comment]
[I've stepped down as a maintainer of the plugin](https://github.com/fgrehm/vagrant-lxc/issues/375) and I'm no longer maintaining this repo. Feel free to use it as a starting point for your own boxes and if you need any help with that just LMK! :beers:
