### ISSUE TITLE
Makefile:36: recipe for target '6' failed make: *** [6] Error 127

### ISSUE THREAD

**Issue by visibilityspots** [fgrehm/vagrant-lxc-base-boxes#23]
I had this issue when trying to create a vagrant-lxc-base-box based on centos on my archlinux machine. After some digging around I found out the PATH environment variable was missing 2 directories to process:
- /usr/sbin
- /bin

When I added those to my .bashrc everything went smooth.

``` bash
export PATH="${PATH}:/usr/sbin:/bin"
```

I don't know if this can be tackled somewhere from within one of the common scripts. I only wanted to share the issue and solution I came through to get this nifty piece of software working :)

**Comment by fgrehm** [comment]
Cool, if someone else experience this problem please raise your hand so we can figure out how to better handle that =)
