### ISSUE TITLE
systemd-journald eats all cpu

### ISSUE THREAD

**Issue by glenux** [fgrehm/vagrant-lxc-base-boxes#36]
I built a Debian Jessie box with your scripts. Everything went fine during the build process.
However, when running the box with ``vagrant up``, systemd-journald eats 100% of CPU.

It seems related to the following issues : 
* https://lists.linuxcontainers.org/pipermail/lxc-devel/2014-August/010131.html
* http://forums.fedoraforum.org/showthread.php?t=295153

It did not try the suggested fixes yet.

**Comment by fgrehm** [comment]
[I've stepped down as a maintainer of the plugin](https://github.com/fgrehm/vagrant-lxc/issues/375) and I'm no longer maintaining this repo. Feel free to use it as a starting point for your own boxes and if you need any help with that just LMK! :beers:
