### ISSUE TITLE
Support 15.04

### ISSUE THREAD

**Issue by narkisr** [fgrehm/vagrant-lxc-base-boxes#40]
Ubuntu 14.04 is a bit old, adding support to 15.x would really push this project forward

**Comment by fgrehm** [comment]
[I've stepped down as a maintainer of the plugin](https://github.com/fgrehm/vagrant-lxc/issues/375) and I'm no longer maintaining this repo. Feel free to use it as a starting point for your own boxes and if you need any help with that just LMK! :beers:
